@host = http://lazzy-dev-571511097.us-east-1.elb.amazonaws.com

@baseUrl = {{host}}/api/v1

@contentType = application/json

###
GET {{host}}
Content-Type: {{contentType}}

###
GET {{host}}/healthcheck
Content-Type: {{contentType}}

###
GET {{baseUrl}}/todos
Content-Type:  {{contentType}}

###
GET {{baseUrl}}/todos/17068774-be2f-4b9f-8f5c-eb33da063a24
Content-Type:  {{contentType}}

###
POST {{baseUrl}}/todos
Content-Type:  {{contentType}}

{
  "task": "task to do",
  "description": "aqui vai uma descrição"
}

###
PATCH  {{baseUrl}}/todos/e3f55849-8fbc-4639-851c-6f9956626061
Content-Type:  {{contentType}}

{
  "task": "mudar task to do",
  "description": "aqui vai outra descrição"
}

###
DELETE  {{baseUrl}}/todos/e3f55849-8fbc-4639-851c-6f9956626061
Content-Type:  {{contentType}}
